name: IPFS Publish

on:
  push:
    branches:
      - main

jobs:
  ipfs-publish:
    runs-on: self-hosted
    permissions:
      contents: read
      discussions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add folder to IPFS
        id: ipfs_add
        run: |
          CID=$(ipfs add --recursive --cid-version=1 -Q .)
          echo "CID=$CID" >> $GITHUB_ENV

      - name: Prewarm IPFS Gateway
        run: |
          wget --recursive --no-parent --no-host-directories --cut-dirs=1 "https://${{ env.CID }}.eth.sucks/"
          wget --recursive --no-parent --no-host-directories --cut-dirs=1 "https://${{ env.CID }}.eth.sucks/src/"
          wget --recursive --no-parent --no-host-directories --cut-dirs=1 "https://${{ env.CID }}.eth.sucks/assets/"

      - name: Create GitHub Discussion
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Get the commit message
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          COMMIT_SHA=$(git rev-parse --short HEAD)
          
          # Create discussion body
          DISCUSSION_BODY="🚀 **New IPFS Deployment**

          **CID:** \`${{ env.CID }}\`
          **Gateway URL:** https://${{ env.CID }}.eth.sucks/
          **Commit:** [\`$COMMIT_SHA\`](https://github.com/${{ github.repository }}/commit/${{ github.sha }}) - $COMMIT_MESSAGE
          **Deployed at:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')

          ---
          This deployment was automatically published to IPFS and is available at the gateway URL above."
          
          # Check if discussions are enabled and get categories
          CATEGORIES_RESPONSE=$(gh api /repos/${{ github.repository }}/discussions/categories 2>/dev/null || echo "[]")
          
          if [ "$CATEGORIES_RESPONSE" = "[]" ]; then
            echo "Discussions are not enabled on this repository. Skipping discussion creation."
            echo "To enable discussions, go to your repository Settings > Features > Discussions"
            exit 0
          fi
          
          # Try to get the Announcements category ID, fallback to General or first available
          CATEGORY_ID=$(echo "$CATEGORIES_RESPONSE" | jq -r '.[] | select(.name=="Announcements") | .id' 2>/dev/null || echo "")
          
          if [ -z "$CATEGORY_ID" ]; then
            CATEGORY_ID=$(echo "$CATEGORIES_RESPONSE" | jq -r '.[] | select(.name=="General") | .id' 2>/dev/null || echo "")
          fi
          
          if [ -z "$CATEGORY_ID" ]; then
            CATEGORY_ID=$(echo "$CATEGORIES_RESPONSE" | jq -r '.[0].id' 2>/dev/null || echo "")
          fi
          
          if [ -z "$CATEGORY_ID" ]; then
            echo "No discussion categories found. Cannot create discussion."
            exit 1
          fi
          
          # Create the discussion
          gh api \
            --method POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            /repos/${{ github.repository }}/discussions \
            -f title="IPFS Deployment - CID: ${{ env.CID }}" \
            -f body="$DISCUSSION_BODY" \
            -f category_id="$CATEGORY_ID" \
            && echo "Discussion created successfully!" \
            || echo "Failed to create discussion"
