name: IPFS Publish

on:
  push:
    branches:
      - main

jobs:
  ipfs-publish:
    runs-on: self-hosted
    permissions:
      contents: read
      discussions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Add folder to IPFS
        id: ipfs_add
        run: |
          CID=$(ipfs add --recursive --cid-version=1 -Q .)
          echo "CID=$CID" >> $GITHUB_ENV

      - name: Prewarm IPFS Gateway
        run: |
          wget --recursive --no-parent --no-host-directories --cut-dirs=1 "https://${{ env.CID }}.eth.sucks/"
          wget --recursive --no-parent --no-host-directories --cut-dirs=1 "https://${{ env.CID }}.eth.sucks/src/"
          wget --recursive --no-parent --no-host-directories --cut-dirs=1 "https://${{ env.CID }}.eth.sucks/assets/"

      - name: Create Discussion
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=%B)
          DISCUSSION_TITLE="New IPFS Deployment: ${{ env.CID }}"
          DISCUSSION_BODY="**CID:** ${{ env.CID }}%0A**Gateway URL:** https://${{ env.CID }}.eth.sucks/%0A**Commit Message:**%0A${COMMIT_MESSAGE}"
          gh discussion create --repo ${{ github.repository }} --category "Announcements" --title "$DISCUSSION_TITLE" --body "$DISCUSSION_BODY"